name: Dependabot Changelog Entry

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [trunk]

env:
  RUST_LOG: DEBUG
  RUST_BACKTRACE: 1

jobs:
  update-changelog:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v7
    - uses: crambl/dependabot-changelog-writer@trunk
      with:
        push-token: ${{ secrets.PAT_PUSH }}

