name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true

jobs:
  build-artifacts:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
            file_extension: .exe

    runs-on: ${{ matrix.os }}
    env:
      binary_name: dependabot-changelog-writer${{ matrix.file_extension }}

    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@v2

      - name: Build macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          export OPENSSL_INCLUDE_DIR=$(brew --prefix openssl)/include
          export OPENSSL_LIB_DIR=$(brew --prefix openssl)/lib
          cargo build --release

      - name: Build ${{ matrix.os }}
        if: ${{ matrix.os != 'macos-latest' }}
        run: cargo build --release

      - name: Create Archive Folder
        run: mkdir ${{ runner.os }}

      - name: Copy Artifact Windows/MacOs
        if: ${{ matrix.os != 'ubuntu-latest' }}
        run: cp target/release/${{ env.binary_name }} ${{ runner.os }}

      - name: Copy Artifact Linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cp target/release/${{ env.binary_name }} ${{ runner.os }}

      - name: Create Tar Archive
        run: tar -czf ${{ runner.os }}.tgz ${{ runner.os }}

      - name: Store Archive
        uses: actions/upload-artifact@v6
        with:
          name: ${{ runner.os }}
          path: ${{ runner.os }}.tgz

  create-release:
    needs: [build-artifacts]
    runs-on: ubuntu-latest
    name: Create Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v7

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Linux/Linux.tgz,macOS/macOS.tgz,Windows/Windows.tgz"
          tag: v${{ github.event.inputs.version }}

  test-success:
    needs: create-release
    env:
      RUST_LOG: DEBUG
      RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./
        with:
          push-changes: false
        env:
          USE_FAKE_EVENT_JSON: test_data/event_json/minimal_pr_opened.json
